[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "sheet_metal_mfg"
authors = [{ name = "Sanvidhi Tech", email = "info@sanvidhitech.com" }]
description = "Sheet Metal WIP Management for ERPNext V16"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = []

[project.urls]
Homepage = "https://github.com/rskshirsagar/sheet-metal"

[tool.bench.dev-dependencies]
